#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Jan 30 13:01:16 2021
#

import wx

# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class mainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: mainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.BORDER_SIMPLE | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1200, 800))
        self.SetTitle("UniversalTools")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY, style=wx.NB_FIXEDWIDTH | wx.NB_TOP)
        sizer_1.Add(self.notebook_1, 0, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "notebook_1_pane_1")

        sizer_2 = wx.FlexGridSizer(3, 1, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "", style=wx.TE_CHARWRAP | wx.TE_MULTILINE)
        self.text_ctrl_1.SetMinSize((1180, 200))
        sizer_2.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)

        grid_sizer_1 = wx.FlexGridSizer(1, 6, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 3)

        self.combo_box_1 = wx.ComboBox(self.notebook_1_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_1.Add(self.combo_box_1, 0, wx.BOTTOM | wx.RIGHT | wx.TOP, 3)

        self.checkbox_1 = wx.CheckBox(self.notebook_1_pane_1, wx.ID_ANY, "auto")
        grid_sizer_1.Add(self.checkbox_1, 0, wx.ALL, 3)

        self.button_1 = wx.Button(self.notebook_1_pane_1, wx.ID_ANY, "button_1")
        grid_sizer_1.Add(self.button_1, 0, wx.ALL, 3)

        grid_sizer_1.Add((20, 20), 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.notebook_1_pane_1, wx.ID_ANY, "search")
        grid_sizer_1.Add(label_1, 0, wx.ALL, 3)

        self.text_ctrl_2 = wx.TextCtrl(self.notebook_1_pane_1, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.BOTTOM | wx.LEFT | wx.TOP, 3)

        self.grid_1 = wx.grid.Grid(self.notebook_1_pane_1, wx.ID_ANY, size=(1, 1))
        self.grid_1.CreateGrid(15, 3)
        self.grid_1.EnableDragRowSize(0)
        self.grid_1.EnableDragGridSize(0)
        self.grid_1.SetColLabelValue(1, "A")
        self.grid_1.SetMinSize((1180, 700))
        sizer_2.Add(self.grid_1, 0, wx.EXPAND, 0)

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_2, "new tab")

        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_3, "new tab")

        self.notebook_1_pane_4 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_4, "new tab")

        self.notebook_1_pane_5 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_pane_5, "new tab")

        grid_sizer_1.AddGrowableRow(0)
        grid_sizer_1.AddGrowableCol(2)
        grid_sizer_1.AddGrowableCol(3)

        sizer_2.AddGrowableRow(0)
        sizer_2.AddGrowableCol(0)
        self.notebook_1_pane_1.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()
        # end wxGlade

# end of class mainFrame

class mainApp(wx.App):
    def OnInit(self):
        self.mFrame = mainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.mFrame)
        self.mFrame.Show()
        return True

# end of class mainApp

if __name__ == "__main__":
    mApp = mainApp(0)
    mApp.MainLoop()
